"""Update restaurant table schema

Revision ID: c36e1f35adcf
Revises: c6a072af8108
Create Date: 2024-09-14 15:48:13.075956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36e1f35adcf'
down_revision = 'c6a072af8108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('country_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('locality',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('locality_verbose',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('cuisines',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('average_cost_for_two',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('has_table_booking',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('has_online_delivery',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('is_delivering_now',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('switch_to_order_menu',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('price_range',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('aggregate_rating',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('rating_color',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('rating_text',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('votes',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('votes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rating_text',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('rating_color',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('aggregate_rating',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('price_range',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('switch_to_order_menu',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('is_delivering_now',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('has_online_delivery',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('has_table_booking',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('average_cost_for_two',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cuisines',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('locality_verbose',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('locality',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('country_code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
