"""empty message

Revision ID: c6a072af8108
Revises: 
Create Date: 2024-09-14 15:26:11.169916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a072af8108'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('locality', sa.String(length=255), nullable=False),
    sa.Column('locality_verbose', sa.String(length=255), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('cuisines', sa.String(length=255), nullable=False),
    sa.Column('average_cost_for_two', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.Column('has_table_booking', sa.String(length=50), nullable=False),
    sa.Column('has_online_delivery', sa.String(length=50), nullable=False),
    sa.Column('is_delivering_now', sa.String(length=50), nullable=False),
    sa.Column('switch_to_order_menu', sa.String(length=50), nullable=False),
    sa.Column('price_range', sa.Integer(), nullable=False),
    sa.Column('aggregate_rating', sa.Float(), nullable=False),
    sa.Column('rating_color', sa.String(length=50), nullable=False),
    sa.Column('rating_text', sa.String(length=50), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant')
    # ### end Alembic commands ###
